version: "2"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
      - ./backups:/home/backups

  backend:
    build: ./desafio-back
    restart: always
    depends_on:
    - "db"
    ports:
      - 3333:3333
    environment:
      APP_URL: http://localhost:3333
      NODE_ENV: development
      APP_SECRET: SAOHDNIOASUOKP@HOZVKPOHVPZK189273918738912739127U3981
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: docker
      DB_NAME: postgres
      DB_PORT: 5432

  frontend:
    build: ./desafio-front
    restart: always
    depends_on: 
      - "backend"
    ports:
      - 3000:3000
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3333